export declare enum OneDayCalendarAppointmentStatus {
  CHECK_IN = 'CHECK_IN',
  PRE_DIALYSIS = 'PRE_DIALYSIS',
  SERVICE_ENCOUNTERED = 'SERVICE_ENCOUNTERED',
  HD_READING = 'HD_READING',
  POST_DIALYSIS = 'POST_DIALYSIS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
