export enum ViewPermissions {
  ViewTodayPatients = 'PATIENTS_VIEW_TODAY',
  ViewSchedule = 'SCHEDULE_VIEW',
  ViewBillingOrder = 'BILLING_VIEW_ORDER',
  ViewBillingPatient = 'BILLING_VIEW_PATIENT',
  ViewVaccination = 'VACCINATION_VIEW',
  ViewCenterReports = 'REPORT_VIEW_CENTER',
  ViewClinicalReports = 'REPORT_VIEW_CLINICAL_DATA',
  ViewManagementReports = 'REPORT_VIEW_MANAGEMENT_DATA',
  ViewFinancialReports = 'REPORT_VIEW_FINANCIAL_DATA',
  ViewClinicalNotes = 'PATIENT_VIEW_CLINICAL_NOTES',
  ViewRegularReports = 'REPORT_VIEW_REGULAR',
  ViewNurseReports = 'REPORT_VIEW_NURSE',
  ViewAdministrativeReports = 'REPORT_VIEW_ADMINISTRATIVE',
  ViewAdministrativeReportsData = 'REPORT_VIEW_ADMINISTRATIVE_DATA',
  ViewInjectionHistoryReports = 'REPORT_VIEW_INJECTION_HISTORY',
  ViewAllPatientsFull = 'PATIENT_VIEW_FULL',
  ViewAllPatientsShort = 'PATIENT_VIEW_SHORT',
  ViewAnalysesOrders = 'ANALYSES_VIEW_ORDERS',
  ViewAdministrationBilling = 'ADMINISTRATION_VIEW_BILLING',
  ViewAdministrationMachinesManagement = 'ADMINISTRATION_VIEW_MACHINES_MANAGEMENT',
  ViewAdministrationStaffManagement = 'ADMINISTRATION_VIEW_STAFF_MANAGEMENT',
  ViewAdministrationUsersList = 'ADMINISTRATION_VIEW_USERS_LIST',
  ViewAdministrationStaffList = 'ADMINISTRATION_VIEW_STAFF_LIST',
  ViewDialysisMachines = 'DIALYSIS_MACHINE_VIEW',
  StaffView = 'STAFF_VIEW',
}
