// @ts-nocheck
import { ERROR_CODES } from '../global/errors';

export const getAxiosResponseErrorCodeExceptionsList = async () => {
  return [
    ERROR_CODES.ERR_CANCELED,
    ERROR_CODES.ERR_NETWORK,
    ERROR_CODES.HD_PRESCRIPTION_CANNOT_BE_DELETED,
    ERROR_CODES.MEDICATION_CONFIRMATION_FREQUENCY_MISMATCH,
    ERROR_CODES.NO_APPOINTMENTS,
    ERROR_CODES.NEXT_HD_PRESCRIPTION_CANNOT_BE_FOUND,
    ERROR_CODES.LAB_ORDER_NUMBER_ALREADY_EXISTS,
    ERROR_CODES.PATIENT_IS_NOT_UNIQUE,
    ERROR_CODES.DEVICE_IS_NOT_UNIQUE,
    ERROR_CODES.DIALYSIS_CANNOT_BE_STARTED_WITHOUT_HD_ACCESS,
    ERROR_CODES.APPOINTMENT_HAS_OPEN_ENCOUNTER,
    ERROR_CODES.S3_FILE_IS_NOT_FOUND,
    ERROR_CODES.S3_ANTIVIRUS_ERROR,
  ];
};

export const getAxiosResponseErrorUrlExceptionList = async () => {
  return ['/api/pm/notifications'];
};
